#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := /u/msteu_01/local/bin/clang
CXX := /u/msteu_01/local/bin/clang++
LD := $(CXX)
AR := ar
OBJCOPY := objcopy

#Additional flags
PREPROCESSOR_MACROS := DEBUG
INCLUDE_DIRS :=/u/msteu_01/skelcl/include /u/msteu_01/skelcl/libraries/pvsutil/include /u/msteu_01/skelcl/libraries/ssedit/include /u/msteu_01/skelcl/libraries/stooling/include /u/msteu_01/skelcl/libraries/ssedit/libraries/libclang/include
LIBRARY_DIRS :=/u/msteu_01/skelcl/buildDebug/src /u/msteu_01/skelcl/buildDebug/libraries/pvsutil/src /u/msteu_01/skelcl/buildDebug/libraries/ssedit/src 
LIBRARY_NAMES :=SkelCL pvsutil ssedit
ADDITIONAL_LINKER_INPUTS :=
MACOS_FRAMEWORKS :=

CFLAGS := -ggdb -ffunction-sections -O3 -std=c++11
CXXFLAGS := -ggdb -ffunction-sections -O3 -std=c++11 
ASFLAGS :=
LDFLAGS := -Wl,-gc-sections -rpath /u/msteu_01/skelcl/libraries/ssedit/libraries/libclang/lib
COMMONFLAGS :=

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
